CREATE TABLE ORDERS (
    ORDER_ID     NUMBER(12) CONSTRAINT ORDER_ID_PK PRIMARY KEY,
    ORDER_DATE   DATE DEFAULT SYSDATE CONSTRAINT ORDER_DATE_NN NOT NULL,
    ORDER_MODE  VARCHAR2(8)CONSTRAINT ORDER_MODE_CHK CHECK(ORDER_MODE IN('direct','online')),
    CUSTOMER_ID     NUMBER(6) CONSTRAINT ORDER_CUSTOMER_ID_NN NOT NULL,
    ORDER_STATUS NUMBER(2),--0: 주문중, 1: 주문완료, 2: 취소, 3: 발송4: 수취
    SALES_ID    NUMBER(6),--판매사원번호
    CONSTRAINT ORDER_SALES_ID_FK FOREIGN KEY(SALES_ID) REFERENCES EMP(EMPNO)
    );

CREATE SEQUENCE ORDER_SEQ
    INCREMENT BY 1 
    START WITH 1 
    MINVALUE 1 
    MAXVALUE 999999999999 
    NOCYCLE 
    CACHE 30;

DROP SEQUENCE ORDER_SEQ;
SELECT ORDER_SEQ.NEXTVAL FROM DUAL;
SELECT ORDER_SEQ.CURRVAL FROM DUAL;

SELECT TO_CHAR(ORDER_SEQ.CURRVAL,'FM00000000') FROM DUAL;

ALTER SEQUENCE ORDER_SEQ INCREMENT BY -2;


DROP TABLE EP2;
CREATE TABLE EP AS SELECT ENAME, JOB, SAL FROM EMP;
CREATE TABLE EP2 AS SELECT EMPNO, ENAME, JOB, SAL FROM EMP;
ALTER TABLE EP ADD(NO NUMBER(12));

SELECT * FROM EP2;
UPDATE EP SET NO = (ORDER_SEQ.NEXTVAL) WHERE NO IS NULL;

COMMIT;
ROLLBACK;
SELECT ORDER_SEQ.CURRVAL FROM DUAL;

SELECT ORDER_SEQ.NEXTVAL FROM DUAL;

SELECT EMPNO, ENAME, ORDER_SEQ.NEXTVAL FROM EP2;


SELECT * FROM ORDERS;

@C:/SQLDEV/SQLF/03_ORDER_TBL.sql;
SELECT ORDER_SEQ.NEXTVAL FROM DUAL;
SELECT ORDER_SEQ.CURRVAL FROM DUAL;

SELECT * FROM EMP;
SELECT * FROM ORDERS;
INSERT INTO ORDERS(ORDER_ID, ORDER_MODE, CUSTOMER_ID, ORDER_STATUS, SALES_ID)
VALUES(ORDER_SEQ.NEXTVAL, 'direct', 166, 1, 7499);

INSERT INTO ORDERS(ORDER_ID, ORDER_DATE, ORDER_MODE, CUSTOMER_ID, ORDER_STATUS, SALES_ID)
VALUES(ORDER_SEQ.NEXTVAL,SYSDATE, 'online', 135, 2, 7844);

COMMIT;
INSERT INTO ORDERS(ORDER_ID,ORDER_DATE,ORDER_MODE,CUSTOMER_ID,ORDER_STATUS,SALES_ID)
VALUES(ORDER_SEQ.NEXTVAL,SYSDATE,'online',135,2,7844);
ROLLBACK;


INSERT INTO ORDERS(ORDER_ID,ORDER_DATE,ORDER_MODE,CUSTOMER_ID,ORDER_STATUS,SALES_ID)
VALUES(ORDER_SEQ.NEXTVAL,SYSDATE,'direct',135,4,7844);
SELECT * FROM ORDERS;
INSERT INTO ORDERS(ORDER_ID,ORDER_MODE,CUSTOMER_ID,ORDER_STATUS,SALES_ID)
VALUES((SELECT MAX(ORDER_ID)+1 FROM ORDERS),'direct',335,4,7654);

SELECT * FROM ORDER_ID;
CREATE TABLE ORDER_ID(ORDER_SEQ NUMBER(12));
INSERT INTO ORDER_ID VALUES(100);
COMMIT;

/*
DECLARE
    V_ORDER_SEQ NUMBER(12);
BEGIN
    SELECT ORDER_SEQ INTO V_ORDER_SEQ
    FROM ORDER_ID
    FOR UPDATE;
    
    INSERT INTO ORDERS(ORDER_ID, ORDER_MODE,CUSTOMER_ID,ORDER_STATUS,SALES_ID)
    VALUES(V_ORDER_SEQ, 'direct',3320,2,7369);

    UPDATE ORDER_ID SET ORDER_SEQ = ORDER_SEQ+1;
    COMMIT;
END;
*/


ALTER SEQUENCE ORDER_SEQ
    INCREMENT BY 1
    START WITH 10
    MAXVALUE 999999999999
    MINVALUE 1
    NOCYCLE
    CACHE 30;


SELECT LPAD(ORDER_SEQ.CURRVAL,8,0) FROM ORDER_ID;

ALTER SEQUENCE ORDER_SEQ INCREMENT BY 9;
ALTER SEQUENCE ORDER_SEQ INCREMENT BY 1;

SELECT ORDER_SEQ.NEXTVAL FROM DUAL;
SELECT ORDER_SEQ.CURRVAL FROM DUAL;
