CREATE TABLE DEPT2 (
    DEPTNO VARCHAR2(2) CONSTRAINT DEPT2_DEPTNO_PK PRIMARY KEY,
    DNAME VARCHAR2(10) CONSTRAINT DEPT2_DNAME_NN NOT NULL
);
CREATE TABLE 사원(
    사번 VARCHAR2(8) PRIMARY KEY,
    이름 VARCHAR2(10),
    DEPTNO VARCHAR2(2) NOT NULL,
    CONSTRAINT EMPLEE_DEPT2_DEPTNO_FK FOREIGN KEY(DEPTNO) REFERENCES DEPT2(DEPTNO)
);