CREATE TABLE 何辑(
    何辑ID VARCHAR2(2) CONSTRAINT DEPARTMENT_何辑ID_PK PRIMARY KEY,
    何辑疙 VARCHAR2(10)
    );

CREATE TABLE EMPLEE(
    EMPID VARCHAR2(8),
    何辑ID VARCHAR2(2),
    CONSTRAINT EMPLEE_何辑_何辑ID_FK FOREIGN KEY(何辑ID) REFERENCES 何辑(何辑ID)
);

DESC 何辑;
DESC EMPLEE;