CREATE TABLE CUST3 (
    ID VARCHAR2(8) NOT NULL CONSTRAINT CUST3_ID_UK UNIQUE,
    PWD VARCHAR2(8) NOT NULL,
    NAME VARCHAR2(20),
    SEX CHAR(1) DEFAULT 'M' CONSTRAINT CUST3_SEX_CK CHECK (SEX IN ('M','F')),
    MOBILE VARCHAR2(14) UNIQUE,
    AGE NUMBER(3) DEFAULT 18
    );