CREATE TABLE PRODUCT (
    PRODUCT_GROUP_CD CHAR(4) ,
    PRODUCT_CATEGORY_CD CHAR(4),
    PRODUCT_CATEGORY_NM VARCHAR2(100) NOT NULL,
    PRODUCT_CATEGORY_DESC VARCHAR2(1000),
    USE_YN CHAR(1) DEFAULT 'N' CONSTRAINT PRODUCT_USE_CK CHECK (USE_YN IN ('Y','N')),
    CONSTRAINT PRODUCT PRIMARY KEY(PRODUCT_GROUP_CD,PRODUCT_CATEGORY_CD)
    );

