CREATE TABLE USERPRODUCT(
    ID VARCHAR2(15) UNIQUE NOT NULL,
    CNT NUMBER DEFAULT 0
    );
COMMIT;
TRUNCATE TABLE USERPRODUCT;
SELECT * FROM USERPRODUCT;

            
INSERT INTO USERPRODUCT(ID,CNT) VALUES('KIM123',5);
INSERT INTO USERPRODUCT(ID,CNT) VALUES('KOPO123',0);
INSERT INTO USERPRODUCT(ID,CNT) VALUES('HIHI1',6);
INSERT INTO USERPRODUCT(ID,CNT) VALUES('YOON23',45);
INSERT INTO USERPRODUCT(ID,CNT) VALUES('PARK00',100);
INSERT INTO USERPRODUCT(ID,CNT) VALUES('HAPPY09',25);
COMMIT;


--------------------------------------------------------



SET SERVEROUTPUT ON FORMAT WRAP;
ACCEPT GET_IDD PROMPT '받는사람을 입력하세요.'
ACCEPT GIVE_IDD PROMPT '보내는 사람을 입력하세요.'

DECLARE
    --받는사람
    GET_ID VARCHAR2(15);
    YOURCNT NUMBER;
    --주는사람
    GIVE_ID VARCHAR2(15):='YOON23';
    MYCNT NUMBER;
    ZERO_EXCEPTION EXCEPTION;
BEGIN
    -- 외부에서 값 입력받기
    GET_ID := &GET_IDD;
    GIVE_ID := &GIVE_IDD;

    SELECT ID,CNT INTO GET_ID,YOURCNT FROM USERPRODUCT@test_link WHERE ID = GET_ID;
    IF GET_ID IS NULL THEN
    RAISE NO_DATA_FOUND;
    END IF;

    SELECT ID,CNT INTO GIVE_ID,MYCNT FROM USERPRODUCT@test_link WHERE ID = GIVE_ID;
    IF GIVE_ID IS NULL THEN
    RAISE NO_DATA_FOUND;
    END IF;
    IF MYCNT = 0 THEN
    RAISE ZERO_EXCEPTION;
    END IF;
            
    UPDATE USERPRODUCT@test_link
        SET CNT = (MYCNT-1)
        WHERE ID = GIVE_ID;
    
    UPDATE USERPRODUCT@test_link
        SET CNT = (YOURCNT+1)
        WHERE ID = GET_ID;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('FROM '||GIVE_ID);
    DBMS_OUTPUT.PUT_LINE('TO '||GET_ID);
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('ID가 존재하지 않습니다!');
        ROLLBACK;
        
        WHEN ZERO_EXCEPTION THEN
        DBMS_OUTPUT.PUT_LINE('재고가 부족합니다!');
        ROLLBACK;
END;
