--1. 고객 중 동명이인 TOP 10.
SELECT C.NAME AS "이름"
FROM (SELECT NAME, COUNT(*) AS CNT 
        FROM CUSTOMER 
        GROUP BY NAME 
        ORDER BY CNT DESC) C
WHERE ROWNUM <= 10;

--2. 2018년 가장 많이 구매한 고객 100명
SELECT TO_CHAR(C100.CNT,'999,999,999,999') AS "구매회수", CS.NAME AS "고객이름" ,CS.ADDRESS1||CS.ADDRESS2 AS "주소"
FROM (
        SELECT O.CUSTOMER_ID AS CID, O.CNT
        FROM (SELECT CUSTOMER_ID, SUM(ORDER_TOTAL) AS TOTAL , COUNT(ORDER_TOTAL) AS CNT
            FROM ORDERS 
            WHERE ORDER_DT BETWEEN '2018/01/01' AND '2018/12/31' AND STATUS IN(1,5,6,7,8,9,10)
            GROUP BY CUSTOMER_ID
            ORDER BY TOTAL DESC) O 
        WHERE ROWNUM <= 100 ) C100, CUSTOMER CS
WHERE C100.CID = CS.ID;



--3. 2019년에 가장 많이 팔린 제품.
SELECT  P.PID, PD.NAME, P.QSUM, P.QAVG
FROM (
        SELECT OI.PRODUCT_ID AS PID, SUM(OI.QUANTITY) AS QSUM, TRUNC(SUM(OI.QUANTITY)/COUNT(*),2) AS QAVG
        FROM (SELECT DISTINCT ID FROM ORDERS WHERE ORDER_DT BETWEEN '2019/01/01' AND '2019/12/31') O, ORDER_ITEMS OI
        WHERE O.ID = OI.ORDER_ID
        GROUP BY OI.PRODUCT_ID
        ORDER BY QSUM) P, PRODUCT PD
WHERE P.PID = PD.ID AND ROWNUM <= 10;


--4. 서울 거주 고객중 여성비율이 가장 많은 구.
SELECT FF.LOCA, FF.구별전체고객수, FF.여성고객수, TRUNC((FF.여성고객수/FF.구별전체고객수)*100,2) AS "여성고객비율"
FROM (
    SELECT F.LOCA, COUNT(F.GENDER) AS "구별전체고객수", SUM(DECODE(F.GENDER,'F',1,0)) AS "여성고객수"
    FROM (
        SELECT DECODE(C.LOC,'초구','서초구','대문구','동대문구',C.LOC) AS LOCA, GENDER
        FROM (
                SELECT RTRIM(SUBSTR(LTRIM(ADDRESS1,'서울 '),0,INSTR(LTRIM(ADDRESS1,'서울 '),' ')),' ') AS LOC, GENDER
                FROM CUSTOMER WHERE ADDRESS1 LIKE '서울%') C 
        ) F
    GROUP BY F.LOCA ORDER BY 여성고객수 DESC) FF
WHERE ROWNUM <= 10;




--5. 2020년에 가장 많이 구매한 고객 100명을 관리하는 사원
SELECT E.DEPTNO AS "부서번호", E.EMPNO AS "사원번호", E.ENAME AS "사원이름", COUNT(CST.ID) AS "고객수"
FROM (
SELECT CID.CUSTOMER_ID AS ID, C.ACCOUNT_MGR AS MGR
FROM (
    SELECT O.CUSTOMER_ID, SUM(O.ORDER_TOTAL) AS TOTAL 
    FROM ORDERS O WHERE ORDER_DT BETWEEN '2020/01/01' AND '2020/12/31' 
    GROUP BY CUSTOMER_ID 
    ORDER BY TOTAL DESC
    ) CID, CUSTOMER C
WHERE CID.CUSTOMER_ID = C.ID AND ROWNUM <= 100) CST, EMP E
WHERE E.EMPNO = CST.MGR
GROUP BY E.DEPTNO, E.EMPNO, E.ENAME
ORDER BY 부서번호 ;


--10.거주지역별 남녀 고객비율 조회
SELECT T.ADDRESS,COUNT(T.GENDER) AS "총고객수"
FROM (
SELECT DECODE(SUBSTR(ADDRESS1,1,INSTR(ADDRESS1,' ')),
                'uC778천 ','인천',SUBSTR(ADDRESS1,1,INSTR(ADDRESS1,' '))) AS ADDRESS, GENDER
FROM CUSTOMER ) T
GROUP BY T.ADDRESS;
